name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4c442972f77e6cda540ebd2dc24be1b634b8e4a5d4a0395a00a28bfc32d1a33"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
