name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e151b24a7cb6bc289aa9d82224c3c4503382cfcc88ec1c7422723280af36e543"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
