name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f72558f6cc89b35816bd8910cac595477e8da8a64570cc8b50171aafc1e9f1d4"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
