name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77a40af426d8d8c4a7d9b1600dd78ea14fd8cd3b4d0346e61d972db81da10036"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
