name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1236d4334a185db1289d84d207675bd69c10fcbff128b132314434cef489a84"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
