name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbe85b8b89d417d0dc1d65099eef5aacbd9e1d1b1f19f7a8063a8a9125867ac7"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
