name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b32ad211bf4dec57e54e26074e8dc211124165dc3fe7ce6cde5cdda9a1e7a2"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
