name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "574ce5b8a0374572b8dd7a270ddb63fe5e5f01610242257dbf4788ce67f6b928"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
