name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af8331970bfd39237a1e9d449066330b182cc6ebe15dd1b1b1d71a7fee7793b6"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
