name = "Fabricated-Adventures"
author = "AgentK"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "050805caa2c36bf9aa3bd803db5881e1c405f0b5f731871fb19dd975b1b7fb33"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
