# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				arrow = true
				cow = true
				fox = true
				pig = true
				pillager = true
				skeleton = true
				bat = true
				husk = true
				area_effect_cloud = true
				rabbit = true
				zombie = true
				sheep = true
				player = true
				item = true
				stray = true
				potion = true
				wolf = true
				zombie_villager = true
				item_frame = true
				phantom = true
				cave_spider = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.naturalist]
				zebra = true
				rattlesnake = true
				snail = true
				tortoise = true
				coral_snake = true
				bear = true
				cardinal = true
				lizard = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				creeperling = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				cave_enderman = true

			[light_sources.settings.entities.sihywtcamd]
				cobweb = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true

			[light_sources.settings.entities.mobz]
				honey_slime = true
				tank_zombie = true
				bigboss = true
				templar = true
				lost_skeleton = true
				overgrown_skeleton = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true

			[light_sources.settings.entities.creeperoverhaul]
				snowy_creeper = true
				bamboo_creeper = true
				desert_creeper = true
				jungle_creeper = true
				cave_creeper = true
				hills_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.zombies_plus]
				crossbow_zombie = true
				runner_zombie = true
				shrieker_zombie = true
				bow_zombie = true
				leaper_zombie = true
				slow_zombie = true
				axe_zombie = true
				cave_zombie = true
				brute_zombie = true

			[light_sources.settings.entities.artifacts]
				mimic = true

